name: Backend Tests
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'backend/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install deps
        working-directory: backend
        run: npm ci
      - name: Unit tests (deterministic)
        working-directory: backend
        env:
          NODE_ENV: test
          ENABLE_LLM_TESTS: '0'
          CI: '1'
          SCAN_FAKE_DELAY_MS: '5'
        run: npm run test:ci
      - name: Stability loop (3x)
        working-directory: backend
        env:
          NODE_ENV: test
          ENABLE_LLM_TESTS: '0'
          CI: '1'
          STABILITY_LOOPS: '3'
          SCAN_FAKE_DELAY_MS: '5'
        run: npm run test:stability
